### ISSUE TITLE
Dev items remaining for first pass 

### ISSUE THREAD

**Issue by suziejprince** [gocd/gocd-trial#5]
MUST 

- [x] Remove server ID from data sharing
Write tests to ensure:
- [x] No secrets are checked in to config.
- [x] No `<agents/>` tag is checked in to config/
- [x] No server ID exists in DB.
- [x] Consider whether we want to randomize agent auto-register key. If so, do it.

NICE TO HAVE 

- [ ] Add ability to understand if someone is using it 
- [x] Make it super easy for someone to push changes w/o having to open a shell inside a running docker container

**Comment by arvindsv** [comment]
All done in https://github.com/gocd/gocd-trial-builder
